### PR TITLE
Print (up to 3) pressing keys on OLED

### PR DESCRIPTION
**Pull request by ryo33**
It replaces the last section of the "Key" row on OLED with printing currently pressing (aka. not released) keys up to 3 keys. It shows the key state reactively. This kind of reactivity would allow us to easily diagnose misfunctioned behavior.
The reason I chose the section for placing this is that, ultimately, it does not provide additional information than the keycode section.
A huge downside is that it increases the firmware size as 128 bytes (in my build environment).

`27628/28672 (96%, 1044 bytes free)` 
to
`27756/28672 (96%, 916 bytes free)`

https://github.com/Yowkees/keyball/assets/8780513/f118a390-f6e3-48f5-8b7d-9cfc16975d95

### CODE REVIEW

**Comment by Yowkees** [comment]
Hi. Printing pressing 3 keys is great idea!
It will be helpful for soldering debug.

I would like to hear about this from keyball firmware developers.
Thank you very much.

**Comment by koron** [comment]
Looks great idea.

I'll merge this with some changes.

**Comment by koron** [comment]
I'll merge and refine with https://github.com/Yowkees/keyball/pull/506

**Comment by koron** [comment]
This is merged with #506. Thank you for the suggestion

**Pull request merged**
